on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node index.js
      - run: echo "DISCORD_TOKEN is $DISCORD_TOKEN"
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
