on:
  workflow_dispatch: # Allows manual trigger
  schedule: # Schedules the workflow to run every 5 hours
    - cron: "0 */5 * * *" # Cron expression for every 5 hours

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Run Node.js Script
        run: node index.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
